// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJrgFcO0xW15-3GePC5bXLG-nDJktElXU',
    appId: '1:387957106808:web:c13c7e832b4ef55fe4658d',
    messagingSenderId: '387957106808',
    projectId: 'cs321-just-eat-it',
    authDomain: 'cs321-just-eat-it.firebaseapp.com',
    storageBucket: 'cs321-just-eat-it.appspot.com',
    measurementId: 'G-LSD37FQKB2',
  );
}
